version: "3"

services:

    api:
        container_name: api
        build: .
        volumes:
            - ../api:/app
        ports:
            - 5000:5000
        env_file:
            - ../.env